image: alpine/edge
packages:
  - curl
  - libx11-dev
  - libxi-dev
  - mesa-dev
sources:
  - https://git.sr.ht/~theoparis/dyadikos
tasks:
  - install: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
      . .cargo/env
      rustup run --install nightly cargo --version --verbose
  - build: |
      . .cargo/env
      cd dyadikos
      cargo +nightly fmt -- --check
      RUSTFLAGS="-Dwarnings" cargo +nightly clippy -- -D warnings
  - test: |
      . .cargo/env
      cd dyadikos
      cargo test
triggers:
  - action: email
    condition: failure
    to: Theo Paris <theoparisdesigns@gmail.com>
