[package]
name = "dyadikos-editor"
version = "0.0.1"
edition = "2021"

[dependencies]
dyadikos = { path = "../core" }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
miniquad = "*"
anyhow = "*"
